runtime: python
entrypoint: gunicorn -b :$PORT index:app

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.8"

env_variables:
  OPENAI_API_KEY : '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'
  TOKEN : 'EAADWtKt4LVMBAJ9zRISN942X6W9ZA6jNixSamfXcjsUxkhIfjzoHAmJTImjAGFwjZBgUkOVmZAcspmZB4KBCxWcPPLNzz6LkBYGXzO9JmMR5kPYy5XszweoViqgxO87mCZAMhvqHRRMv5j1Igtjd5gWoXfD94nHjclr2HV7VxSJaOlnubHVeBdgzFANkBTQNbhP327lC1rkXZBo4jXO7WN'
  MYTOKEN : 'asif'